### ISSUE TITLE
We Are Experiencing Technical Difficulties. 현재 기술적 문제에 직면하고 있습니다. 

### ISSUE THREAD

**Issue by Outfit8TSB** [GAME-CLI-SRV-DEV/Radioactive#1]
파일 이름: ```RadioActive-Leavesclip-1.20.6-R0.1-SNAPSHOT-reobf.jar```
파일 타입: ```Reobfuscated```
페이퍼클립 여부: ```leavesclip 2```
```
Starting org.bukkit.craftbukkit.Main
Exception in thread "ServerMain" java.lang.ExceptionInInitializerError
        at io.papermc.paper.ServerBuildInfo.buildInfo(ServerBuildInfo.java:69)
        at org.bukkit.craftbukkit.Main$1.<init>(Main.java:146)
        at org.bukkit.craftbukkit.Main.main(Main.java:37)
        at org.leavesmc.leavesclip.Leavesclip.lambda$main$0(Leavesclip.java:45)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Encountered an exception loading service interface io.papermc.paper.ServerBuildInfo
        at net.kyori.adventure.util.Services.service(Services.java:64)
        at io.papermc.paper.ServerBuildInfo$1Holder.<clinit>(ServerBuildInfo.java:66)
        ... 5 more
Caused by: java.util.ServiceConfigurationError: io.papermc.paper.ServerBuildInfo: Provider io.papermc.paper.ServerBuildInfoImpl could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
        at net.kyori.adventure.util.Services.service(Services.java:61)
        ... 6 more
Caused by: java.lang.IllegalStateException: Game version not set
        at net.minecraft.SharedConstants.b(SharedConstants.java:163)
        at io.papermc.paper.ServerBuildInfoImpl.<init>(ServerBuildInfoImpl.java:46)
        at io.papermc.paper.ServerBuildInfoImpl.<init>(ServerBuildInfoImpl.java:36)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
        ... 9 more
```
이 오류로 인해, --v 명령줄은 비활성화되었으며, 버킷이름-시간-BukkitAPI버전-빌드번호-커밋로 나옵니다. 예시: 
```
빌드 태그
RadioActive-2024-06-30T13:24:13Z-1.20.6-R0.1-SNAPSHOT-DEV-8101e2f
RadioActive-2024-07-12T18:54:13Z-1.21-R0.1-SNAPSHOT-46-123abcd
```

**Comment by Outfit8TSB** [comment]
--v 명령줄 제거되었습니다
